export const WORDS: string[] = [
  // Top 100 most common English words
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their",
  "what", "so", "up", "out", "if", "about", "who", "get", "which", "go",
  "me", "when", "make", "can", "like", "time", "no", "just", "him", "know",
  "take", "people", "into", "year", "your", "good", "some", "could", "them",
  "see", "other", "than", "then", "now", "look", "only", "come", "its", "over",
  "think", "also", "back", "after", "use", "two", "how", "our", "work",
  "first", "well", "way", "even", "new", "want", "because", "any", "these",
  // Common words 100-200
  "give", "day", "most", "us", "great", "should", "where", "much", "through",
  "before", "world", "still", "between", "under", "while", "place", "such",
  "however", "without", "another", "thought", "never", "against", "together",
  "around", "during", "always", "nothing", "everything", "small", "large",
  "found", "different", "since", "seem", "point", "call", "home", "last",
  "long", "need", "both", "hand", "part", "high", "keep", "become", "important",
  "every", "each", "begin", "child", "turn", "those", "family", "side",
  "already", "real", "right", "leave", "few", "might", "left", "right",
  "move", "live", "water", "still", "line", "put", "end", "system", "city",
  "game", "face", "house", "room", "reason", "write", "kind", "problem",
  "number", "help", "fact", "try", "hand", "head", "body", "three", "state",
  "case", "whole", "must", "stand", "free", "open", "change", "white",
  "four", "start", "run", "play", "order", "feel", "name", "car", "old",
  "school", "question", "hand", "study", "read", "story", "second", "early",
  "close", "far", "near", "mean", "learn", "money", "food", "world",
  "land", "form", "group", "company", "party", "country", "enough",
  "example", "happy", "door", "sure", "such", "report", "grow", "tree",
  "today", "bring", "boy", "girl", "man", "woman", "guy", "bit",
  // Additional common words 200-250
  "lost", "eye", "big", "small", "red", "green", "black", "blue",
  "hot", "cold", "warm", "fast", "slow", "easy", "hard", "good", "bad",
  "rich", "poor", "young", "old", "new", "early", "late", "short",
  "deep", "wide", "tall", "low", "next", "full", "empty", "dry",
  "wet", "soft", "hard", "sweet", "sour", "loud", "quiet", "busy",
];
