export const WORDS: string[] = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their",
  "what", "so", "up", "out", "if", "about", "who", "get", "which", "go",
  "me", "when", "make", "can", "like", "time", "no", "just", "him", "know",
  "take", "people", "into", "year", "your", "good", "some", "could", "them",
  "see", "other", "than", "then", "now", "look", "only", "come", "its", "over",
  "think", "also", "back", "after", "use", "two", "how", "our", "work", "first",
  "well", "way", "even", "new", "want", "because", "any", "these", "give", "day",
  "most", "us", "through", "should", "over", "world", "still", "try", "school",
  "keep", "never", "last", "let", "between", "city", "tree", "river", "mountain",
  "sky", "blue", "green", "red", "black", "white", "house", "road", "friend",
  "love", "hate", "fear", "hope", "wish", "dream", "sleep", "wake", "eat", "drink",
  "run", "walk", "jump", "sit", "stand", "talk", "hear", "see", "feel", "think",
  "find", "lose", "give", "take", "bring", "keep", "show", "tell", "ask", "write",
  "read", "learn", "teach", "play", "game", "book", "pen", "paper", "computer",
  "phone", "music", "song", "movie", "art", "color", "shape", "size", "big",
  "small", "fast", "slow", "hard", "soft", "loud", "quiet", "hot", "cold",
  "rain", "snow", "wind", "sun", "moon", "star", "cloud", "storm", "light",
  "dark", "near", "far", "high", "low", "left", "right", "top", "bottom"
];
